### ISSUE TITLE
Add USB-C connector

### ISSUE THREAD

**Issue by chatelao** [gab-k/RP2040-Decoder#14]
I love this project and think it has the potential to shake the Model-Railroad community.

The great thing about the RP2040 is the included permanent ROM uf2 Bootloader. Yes, adding a USB-C interface will cost some realestate, BUT would lower the bar for developers signifcantly, removing the need to understand SWD programming at all.

I think, as soon as the Software compiles in a Ardunino environment, the support of entry enthusiast will explode.

The "adafruit QT RP2040" may be a good source to copy-paste ideas?
- https://learn.adafruit.com/assets/101678

**Comment by gab-k** [comment]
I agree and also thought about adding the USB connector before. If I have the time I might change the PCB with an optional USB connector on the back side in the future.

**Comment by chatelao** [comment]
It would be great - I tried to do it myself, but failed misarably.

I would like to try to add a Märklin (MM2) supported firmware version.

btw: Reading and Writing a config file with all CVs and Parameters over a USB-C  could greatly simplyfing the process of decoder setup. Even sound files in a microcontroller compatible format could be added "drag n drop".

**Comment by chatelao** [comment]
Oh, die USB Version sieht sehr schön aus. Ich hab mir überlegt, ob man mit senkrechten Buchsen etwas weniger Platz auf der Platine bräuchte.
